version: '3.5'
services:
    server:
        image: nginx:latest
        ports:
          - "${EXPOSE_HTTP}:80"
          - "${EXPOSE_HTTPS}:443"
        env_file:
          - .env
        depends_on:
          - php
        volumes:
          - ./docker/nginx/conf.d:/etc/nginx/conf.d
          - ./docker/nginx/entrypoint.sh/:/usr/local/bin/entrypoint.sh/
          - ./docker/nginx/nginx.conf/:/etc/nginx/nginx.conf/
          - ./:/var/www
          - ./frontoffice/runtime/nginxlogs:/var/log/nginx
          - ${SSL_CERTIFICATE_VOLUME}
        entrypoint: ["/usr/local/bin/entrypoint.sh"]
        command: ["nginx", "-g", "daemon off;"]
    php:
        build: 
            context: ./docker/php
            args:
              - uid=${UID}
              - gid=${GID}
              - username=${USERNAME}
        env_file:
          - .env
        volumes:
          - ./:/var/www
        user: $USERNAME
    node-cli:
        build: 
            context: ./docker/node-cli
        volumes:
          - ./:/data
    db:
        image: mariadb:latest
        env_file:
          - .env
        volumes:
          - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
          - "5001:80"
        depends_on:
          - db
        volumes:
          - db_data:/var/lib/mysql
volumes:
    db_data: